import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Button, ButtonGroup } from "@chakra-ui/react";
import Link from "next/link";
import { useEffect, useState } from "react";
import Image from "next/image";

export default function Home({ MyData }) {
  const [data, setData] = useState([]);

  const GithubInfo = async () => {
    let res = await fetch(`https://rct-201-c3-data.vercel.app/projects`);
    let data = await res.json();
    return setData(data);
  };

  useEffect(() => {
    GithubInfo();
  }, []);

  console.log(data);

  return (
    <div className={styles.container}>
      <Head>
        <title>Akash More</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{ backgroundColor: "#2d3748;" }}>
        <div className={styles.main_div}>
          {MyData.map((el) => (
            <>
              <div>
                <div>
                  <Image
                    src={el.avatar_url}
                    alt="profile-pic"
                    style={{ borderRadius: "50%" }}
                  />
                  <h1>{el.name}</h1>
                  <Link href={el.html_url}>{el.login}</Link>
                  <p>{el.bio}</p>
                  <Button colorScheme="teal" variant="outline">
                    Resume
                  </Button>
                  <Button
                    colorScheme="teal"
                    variant="outline"
                    onClick={() => {
                      el.followers_url;
                    }}
                  >
                    Follow
                  </Button>
                </div>

                <br />
                <div
                  style={{
                    display: "gird",
                    gridTemplateColumns: "repeat(1,1fr)",
                    gap: "5px",
                  }}
                >
                  <Button colorScheme="white" variant="outline">
                    TYPESCRIPT
                  </Button>
                  <Button colorScheme="white" variant="outline">
                    REACT.JS
                  </Button>
                  <Button colorScheme="white" variant="outline">
                    NODE.JS
                  </Button>
                  <Button colorScheme="white" variant="outline">
                    MONGODB
                  </Button>
                  <Button colorScheme="white" variant="outline">
                    GIT
                  </Button>
                  <Button colorScheme="white" variant="outline">
                    REACT-NEXT
                  </Button>
                  <Button colorScheme="white" variant="outline">
                    CHAKRA-UI
                  </Button>
                  <Button colorScheme="white" variant="outline">
                    CSS
                  </Button>
                  <Button colorScheme="white" variant="outline">
                    TAILWIND
                  </Button>
                  <Button colorScheme="white" variant="outline">
                    MUI
                  </Button>
                </div>

                <div></div>
              </div>

              <div>
                <div>
                  <h1>Projects</h1>

                  {data.map((el) =>
                    el.items.map((elem) => (
                      <div key={elem.name}>
                        <h1>Project Name :-{elem.name}</h1>
                        <h1>Project full name :-{elem.full_name}</h1>
                        <h1>Project id :-{elem.id}</h1>
                      </div>
                    ))
                  )}
                </div>
              </div>
            </>
          ))}
        </div>
      </main>
    </div>
  );
}

export async function getServerSideProps() {
  let res = await fetch(`https://rct-201-c3-data.vercel.app/Mydata`);
  let data = await res.json();
  return {
    props: {
      MyData: data,
    },
  };
}
